{
 "title": "hw_dash",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "node_cpu_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{job=~\"node-exporter\", mode=\"idle\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "filesystem available size",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (node_filesystem_size_bytes{job=\"node-exporter\", fstype!~\"tmpfs|aufs|overlay\"} - node_filesystem_free_bytes{job=\"node-exporter\", fstype!~\"tmpfs|aufs|overlay\"}) / node_filesystem_size_bytes{job=\"node-exporter\", fstype!~\"tmpfs|aufs|overlay\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_load1{job=~\"node-exporter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load5{job=\"node-exporter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load15{job=\"node-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "node memory available in Gb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"node-exporter\"} / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}